
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: hust_link
    hostname: hust_link
    ports:
      - '1444:1433'
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=HustLink@
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - '1025:1025'
      - '8025:8025'  # Web UI for viewing emails